server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: DEPATERMENT-SERVICE
          uri: lb://DEPATERMENT-SERVICE
          predicates:
            - Path=/depaterment/**
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
  config:
    import: "optional:configserver:"
    cloud:
      config:
        uri: http://localhost:8888

